### ISSUE TITLE
tracking on nuscenes with customized detection inputs

### ISSUE THREAD

**Issue by hanwen0529** [tusen-ai/SimpleTrack#25]
How can we integrate "customized detections" of nuscenes dataset with the simpletrack pipeline, and obtain the performance score?

**Comment by ziqipang** [comment]
Thanks for asking! @hanwen0529 

1. First, preprocess your customized detection with the contents in [here](https://github.com/TuSimple/SimpleTrack/blob/main/docs/data_preprocess.md#2-detection). Basically, you only need to provide your `json` format detection file.
2. Second, run the inference code as [here](https://github.com/TuSimple/SimpleTrack/blob/main/docs/nuScenes.md#inference-with-simpletrack).
