### ISSUE TITLE
constant velocity model

### ISSUE THREAD

**Issue by ifzhang** [tusen-ai/SimpleTrack#28]
Thanks for your wonderful work! Do you have the code for the constant velocity model on Nuscenes dataset? I tried to implement the constant velocity model but cannot reproduce the results. Is there any preprocessing of the velocity or time stamp? Thank you very much!

**Comment by ziqipang** [comment]
@ifzhang We haven't summarized the code for the constant velocity model yet, but you can check out our `dev` branch for an "uncleaned" implementation. In brief, you only need to change the `motion_model` field in the configuration file to `velo`, as in this [example of Waymo Open Dataset](https://github.com/tusen-ai/SimpleTrack/blob/115d89f15aed5b9c3f8aae54397015aaa27623d1/configs/waymo_configs/vc_velo_iou.yaml#L9).

**Comment by ifzhang** [comment]
I will check the dev branch. Thank you very much!
