### ISSUE TITLE
The asso_thres in waymo config file is different to the value in paper

### ISSUE THREAD

**Issue by sjtuljw520** [tusen-ai/SimpleTrack#29]
Hi, in the paper the asso_thres is set as -0.5. However, I find the value is set as 1.5 in the config file. 
Is there any information I missing?
` asso_thres:
    iou: 0.9
    giou: 1.5`

**Comment by ziqipang** [comment]
The value here means (1 - `threshold`). Thanks for the interest! @sjtuljw520

**Comment by sjtuljw520** [comment]
OK, thank you! @ziqipang
