### ISSUE TITLE
how to prepare wayno raw data?

### ISSUE THREAD

**Issue by liuhao123t** [tusen-ai/SimpleTrack#31]
the websit of [wayno dataset](https://waymo.com/intl/en_us/open/download/) ,that include two type dataset ,if i want to to 3d track, should i download the perception type ? and perception type have many versions, each version have many subdirectories，i am very confused which one need to download for [waymo_preprocess](https://github.com/tusen-ai/SimpleTrack/blob/main/docs/data_preprocess.md) to get the handy row wayno data。

**Comment by ziqipang** [comment]
@liuhao123t Thanks for asking!
Yes, please download the perception subset. I think all of the data in the validation set is needed to fully run SimpleTrack on Waymo Open Dataset.

**Comment by liuhao123t** [comment]
@ziqipang Thanks for answering

**Comment by liuhao123t** [comment]
@ziqipang one more question,where is the gt.bin that include ground truth information ? I did not find the file in [waymo dataset](https://console.cloud.google.com/storage/browser/waymo_open_dataset_v_1_2_0;tab=objects?prefix=&forceOnObjectsSortingFiltering=false)

**Comment by ziqipang** [comment]
@liuhao123t Yeah, I remembered this issue, but I cannot find it right now since SimpleTrack was two years ago. I suggest you reach out to Waymo folks or contact with the authors of recent 3D detection / 3D MOT papers, they surely have it at hand.

**Comment by liuhao123t** [comment]
@ziqipang 好嘞
