### ISSUE TITLE
nuscenes evaluation metrics

### ISSUE THREAD

**Issue by ibqing** [tusen-ai/SimpleTrack#33]
I have converted the trace results to nuScenes format and got a .json file（results.json） that conforms to the nuScenes trace specification. However, when I use the official nuScenes repo nuscenes-devkit to evaluate the .json trace result just generated, I get the error as shown below:

input:
python /home/anaconda3/envs/simpletrack/lib/pyton3.7/site-packages/nuscenes/eval/tracking/evaluate.py /home/pointcloud/My/data/nuscenes/2hz/result/Ssimpletrack7/sitelt/SimpleTrack2Hz/results --eval_set val --dataroot /home/pointcloud/My/data/nuscenes/2hz
output:
_ValueError: Length of names must match number of levels in Multiindex._

How should I solve it?

**Comment by ziqipang** [comment]
@ibqing Please use `motmetrics==1.1.3`. The higher version is incompatible with some interfaces of nuScenes and pandas.

**Comment by ibqing** [comment]
Thank you very much！I will try to modify it this way.

**Comment by ibqing** [comment]
I've got it running successfully, thanks!

**Comment by ibqing** [comment]
Hi, I can't download the detection_file.json file of nuscenes-validation_10hz on Dropbox, I tried many times but I can't download it. Can you please send me a detection_file.json file?

**Comment by ziqipang** [comment]
@ibqing Just returned from a trip. What is your email?

**Comment by ibqing** [comment]
Thank you so much for your reply!
My email is: 1101335755@qq.com
