### ISSUE TITLE
Speed of the objects

### ISSUE THREAD

**Issue by cat722** [tusen-ai/SimpleTrack#35]
Hello, Does the tracking result contain information about the speed of the object? If not, how can I get it?
Thanks!

**Comment by ziqipang** [comment]
@cat722 The tracking result does not have velocity. I suggest two approaches:
1. The detection result (e.g. centerpoint), might output the velocities predicted by the neural networks.
2. You can access the internal states of Kalman filter to see the velocities filtered by Kalman filters.
