### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by ndwmath** [tusen-ai/SimpleTrack#38]
Hello, thanks for your great work! I followed the steps in nuScenes.md to reproduce the code.
Since FPS is not mentioned in the output, nor is it described in the paper, what is the inference speed of SimpleTrack in the nuScence dataset?
python tools/main_nuscenes.py \
    --name SimpleTrack2Hz \
    --det_name  detname\
    --config_path configs/nu_configs/giou.yaml \
    --result_folder /mnt/data/nuScenes/nuscenes_simpletrack_res \
    --data_folder /mnt/data/nuScenes/2hz \
    --process 150
Can I use the above script running time to calculate it myself?

**Comment by ziqipang** [comment]
Sure. Using a single process is more fair when comparison.

**Comment by ndwmath** [comment]
thanks!
